services:
  mongodb:
    image: mongo:7
    restart: on-failure
    ports:
      - ${MONGO_PORT:-27017}:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TRUST_MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${TRUST_MONGO_ROOT_PASS}
    volumes:
      - mongo_data:/data/db
  trust:
    image: europe-west1-docker.pkg.dev/moderate-common/moderate-images/trust-service:main
    restart: on-failure
    ports:
      - ${TRUST_PORT:-8081}:8081
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env.trust
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TRUST_MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${TRUST_MONGO_ROOT_PASS}
      MONGO_ENDPOINT: mongodb:27017
      MONGO_DATABASE: ${MONGO_DATABASE:-moderate}
volumes:
  mongo_data: {}
