version: "3"

vars:
  MINIKUBE_MEM: 8G
  MINIKUBE_CPU: 2
  DAGSTER_CHART_VERSION: 1.4.14
  DAGSTER_WEBSERVER_PORT: 8080
  IMAGE_LOCAL_NAME: moderate-dagster
  IMAGE_REMOTE_NAME: agmangas/moderate-dagster
  IMAGE_REMOTE_TAG: latest

env:
  IMAGE_REMOTE_NAME: "{{.IMAGE_REMOTE_NAME}}"
  IMAGE_REMOTE_TAG: "{{.IMAGE_REMOTE_TAG}}"

dotenv: [.env, .env.default]

tasks:
  compose-up:
    desc: Start the Compose stack
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose.dev.yml up -d --build --wait

  minikube-start:
    desc: Start minikube
    cmds:
      - minikube start --memory={{.MINIKUBE_MEM}} --cpus={{.MINIKUBE_CPU}}
    status:
      - minikube status

  build-helm-values:
    desc: Build the Helm values file
    cmds:
      - envsubst < {{.ROOT_DIR}}/values.dev.yaml.template > {{.ROOT_DIR}}/values.dev.yaml

  helm-dagster:
    desc: Install Dagster Helm chart
    cmds:
      - helm repo add dagster https://dagster-io.github.io/helm
      - task: build-helm-values
      - >
        helm upgrade --install dagster dagster/dagster 
        --version {{.DAGSTER_CHART_VERSION}} 
        -f {{.ROOT_DIR}}/values.dev.yaml

  clean:
    desc: Clean up the dev environment
    cmds:
      - minikube delete
      - docker compose -f {{.ROOT_DIR}}/docker-compose.dev.yml down

  start-dev:
    desc: Start the dev environment
    cmds:
      - task: compose-up
      - task: minikube-start
      - task: helm-dagster

  default:
    cmds:
      - task: start-dev

  dagster-webserver:
    desc: Forward the Dagster Webserver port
    cmds:
      - >
        DAGSTER_WEBSERVER_POD_NAME=$(
        kubectl get pods --namespace default 
        -l "component=dagster-webserver" 
        -o jsonpath="{.items[0].metadata.name}"
        ) && kubectl port-forward ${DAGSTER_WEBSERVER_POD_NAME} {{.DAGSTER_WEBSERVER_PORT}}:80

  push-code-image:
    desc: Push the code image to Docker Hub
    cmds:
      - docker build -t {{.IMAGE_LOCAL_NAME}} {{.ROOT_DIR}}
      - docker tag {{.IMAGE_LOCAL_NAME}} {{.IMAGE_REMOTE_NAME}}:{{.IMAGE_REMOTE_TAG}}
      - docker push {{.IMAGE_REMOTE_NAME}}:{{.IMAGE_REMOTE_TAG}}
