version: "3"

vars:
  MINIKUBE_MEM: 8G
  MINIKUBE_CPU: 2
  DAGSTER_CHART_VERSION: 1.4.14
  DAGSTER_WEBSERVER_PORT: 8181
  IMAGE_LOCAL_NAME: moderate-dagster
  IMAGE_REMOTE_NAME: agmangas/moderate-dagster
  IMAGE_REMOTE_TAG: latest
  VENV_NAME: .venv
  SECRETS_ENV_FILE: dagster-secrets.env
  SECRETS_NAME: dagster-secrets

env:
  IMAGE_REMOTE_NAME: "{{.IMAGE_REMOTE_NAME}}"
  IMAGE_REMOTE_TAG: "{{.IMAGE_REMOTE_TAG}}"

dotenv: [.env, .env.default]

tasks:
  clean:
    desc: Clean up the dev environment
    cmds:
      - minikube delete
      - docker compose -f {{.ROOT_DIR}}/docker-compose.dev.yml down
      - cmd: rm values.dev.yaml
        ignore_error: true
      - cmd: rm {{.ROOT_DIR}}/{{.SECRETS_ENV_FILE}}
        ignore_error: true

  compose-up:
    desc: Start the Compose stack
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose.dev.yml up -d --build --wait

  minikube-start:
    desc: Start minikube
    cmds:
      - minikube start --memory={{.MINIKUBE_MEM}} --cpus={{.MINIKUBE_CPU}}
    status:
      - minikube status

  build-helm-values:
    desc: Build the Helm values file
    cmds:
      - envsubst < {{.ROOT_DIR}}/values.dev.yaml.template > {{.ROOT_DIR}}/values.dev.yaml

  build-dagster-secrets-envfile:
    desc: Build the Dagster secrets envfile
    vars:
      SECRETS_PATH: "{{.ROOT_DIR}}/{{.SECRETS_ENV_FILE}}"
    cmds:
      - cmd: rm {{.ROOT_DIR}}/{{.SECRETS_ENV_FILE}}
        ignore_error: true
      - echo "KEYCLOAK_SERVER_URL=http://host.docker.internal:8080/" >> {{.SECRETS_PATH}}
      - echo "KEYCLOAK_ADMIN_USERNAME={{.KEYCLOAK_ADMIN}}" >> {{.SECRETS_PATH}}
      - echo "KEYCLOAK_ADMIN_PASSWORD={{.KEYCLOAK_ADMIN_PASSWORD}}" >> {{.SECRETS_PATH}}
      - echo "POSTGRES_HOST=host.docker.internal" >> {{.SECRETS_PATH}}
      - echo "POSTGRES_PORT=5432" >> {{.SECRETS_PATH}}
      - echo "POSTGRES_USERNAME={{.POSTGRES_USER}}" >> {{.SECRETS_PATH}}
      - echo "POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}}" >> {{.SECRETS_PATH}}

  create-dagster-secrets:
    desc: Create the Dagster secrets
    deps:
      - build-dagster-secrets-envfile
    cmds:
      - kubectl create secret generic {{.SECRETS_NAME}} --from-env-file={{.ROOT_DIR}}/{{.SECRETS_ENV_FILE}}

  install-helm-dagster:
    desc: Install Dagster Helm chart
    cmds:
      - helm repo add dagster https://dagster-io.github.io/helm
      - task: build-helm-values
      - >
        helm upgrade --install dagster dagster/dagster 
        --version {{.DAGSTER_CHART_VERSION}} 
        -f {{.ROOT_DIR}}/values.dev.yaml

  push-code-image:
    desc: Push the code image to Docker Hub
    cmds:
      - docker build -t {{.IMAGE_LOCAL_NAME}} {{.ROOT_DIR}}
      - docker tag {{.IMAGE_LOCAL_NAME}} {{.IMAGE_REMOTE_NAME}}:{{.IMAGE_REMOTE_TAG}}
      - docker push {{.IMAGE_REMOTE_NAME}}:{{.IMAGE_REMOTE_TAG}}

  start-dev-k8s:
    desc: Start the dev environment in the local Kubernetes cluster
    cmds:
      - task: push-code-image
      - task: compose-up
      - task: minikube-start
      - task: create-dagster-secrets
      - task: install-helm-dagster

  forward-k8s-dagster-webserver:
    desc: Forward the Dagster Webserver port
    cmds:
      - >
        DAGSTER_WEBSERVER_POD_NAME=$(
        kubectl get pods --namespace default 
        -l "component=dagster-webserver" 
        -o jsonpath="{.items[0].metadata.name}"
        ) && kubectl port-forward ${DAGSTER_WEBSERVER_POD_NAME} {{.DAGSTER_WEBSERVER_PORT}}:80

  create-venv-dagster-dev:
    desc: Create the Dagster dev virtualenv
    cmds:
      - virtualenv {{.ROOT_DIR}}/{{.VENV_NAME}}
      - "{{.ROOT_DIR}}/{{.VENV_NAME}}/bin/pip install -U -e {{.ROOT_DIR}}/moderate[dev]"

  dagster-dev:
    desc: Run the Dagster dev CLI
    deps:
      - compose-up
      - create-venv-dagster-dev
    env:
      KEYCLOAK_SERVER_URL: http://localhost:8080/
      KEYCLOAK_ADMIN_USERNAME: "{{.KEYCLOAK_ADMIN}}"
      KEYCLOAK_ADMIN_PASSWORD: "{{.KEYCLOAK_ADMIN_PASSWORD}}"
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: "{{.POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{.POSTGRES_PASSWORD}}"
    cmds:
      - cd {{.ROOT_DIR}}/moderate && {{.ROOT_DIR}}/{{.VENV_NAME}}/bin/dagster dev
