import enum


class ResourceNames(enum.Enum):
    KEYCLOAK = "keycloak"
    POSTGRES = "postgres"
    OPEN_METADATA = "open_metadata"


class Variables(enum.Enum):
    KEYCLOAK_SERVER_URL = "KEYCLOAK_SERVER_URL"
    KEYCLOAK_ADMIN_USERNAME = "KEYCLOAK_ADMIN_USERNAME"
    KEYCLOAK_ADMIN_PASSWORD = "KEYCLOAK_ADMIN_PASSWORD"
    KEYCLOAK_MAIN_REALM_NAME = "KEYCLOAK_MAIN_REALM_NAME"
    POSTGRES_HOST = "POSTGRES_HOST"
    POSTGRES_PORT = "POSTGRES_PORT"
    POSTGRES_USERNAME = "POSTGRES_USERNAME"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
    OPEN_METADATA_HOST = "OPEN_METADATA_HOST"
    OPEN_METADATA_PORT = "OPEN_METADATA_PORT"
    OPEN_METADATA_TOKEN = "OPEN_METADATA_TOKEN"
    TRUST_SERVICES_API_URL = "TRUST_SERVICES_API_URL"


class VariableDefaults(enum.Enum):
    KEYCLOAK_MAIN_REALM_NAME = "moderate"
